<script setup lang="ts">
import { exportQualityWorkbook, generateQualityFinal, getJuniorQualityClasses, getQualityClassStudents, getQualityConfig, getQualityFinal, getStudentQuality, getStudentQualitySummary, importQualityWorkbook, lockQualityFinal, saveStudentQualitySemester, updateQualityFinalLevel } from "@/api/quality";
import type { UploadFile, UploadInstance } from "element-plus";
type StudentRow = { studentId: number; code: string; name: string; completedSemesters: number };
const config = ref<any>({ dimensions: [], semesters: [] });
const classes = ref<any[]>([]); const students = ref<StudentRow[]>([]); const clazzId = ref<number>(); const selectedStudent = ref<StudentRow>();
const records = ref<any[]>([]); const summary = ref<any>({ dimensionTotals: {} }); const matrix = reactive<Record<string, Record<string, string>>>({});
const loading = ref(false); const importDialog = ref(false); const importFile = ref<File>(); const uploadRef = ref<UploadInstance>();
const finalRows = ref<any[]>([]); const finalState = ref<any>({ isLocked: 0 }); const finalDialog = ref(false);
function resetMatrix() { Object.keys(matrix).forEach((key) => delete matrix[key]); for (const semester of config.value.semesters ?? []) { matrix[semester] = {}; for (const dimension of config.value.dimensions ?? []) matrix[semester][dimension] = "N/A"; } }
async function loadClasses() { const { data } = await getJuniorQualityClasses(); classes.value = data ?? []; if (!clazzId.value && classes.value.length) { clazzId.value = classes.value[0].id; await loadStudents(); } }
async function loadStudents() { if (!clazzId.value) return; selectedStudent.value = undefined; records.value = []; summary.value = { dimensionTotals: {} }; const { data } = await getQualityClassStudents(clazzId.value); students.value = data ?? []; }
async function loadFinal() { if (!clazzId.value) return; const { data } = await getQualityFinal(clazzId.value); finalRows.value = data?.rows ?? []; finalState.value = data?.state ?? { isLocked: 0 }; }
async function selectStudent(row: StudentRow | null) { if (!row) return; selectedStudent.value = row; resetMatrix(); const [recordResponse, summaryResponse] = await Promise.all([getStudentQuality(row.studentId), getStudentQualitySummary(row.studentId)]); records.value = recordResponse.data ?? []; summary.value = summaryResponse.data ?? { dimensionTotals: {} }; records.value.forEach((record) => { if (matrix[record.semester]) matrix[record.semester][record.dimension] = record.level ?? "N/A"; }); }
async function saveAll() { if (!selectedStudent.value) return ElMessage.warning("请先选择学生"); loading.value = true; try { for (const semester of config.value.semesters) await saveStudentQualitySemester(selectedStudent.value.studentId, semester, matrix[semester]); ElMessage.success("综合素质评价已保存"); await selectStudent(selectedStudent.value); } finally { loading.value = false; } }
function chooseFile(file: UploadFile) { importFile.value = file.raw; }
async function doImport() { if (!clazzId.value || !importFile.value) return ElMessage.warning("请选择要导入的 Excel 文件"); const { data } = await importQualityWorkbook(clazzId.value, importFile.value); const issueText = data.issues?.length ? `，${data.issues.length} 条未匹配/校验提示` : ""; ElMessage.success(`导入完成：匹配 ${data.matchedRows} 行${issueText}`); if (data.issues?.length) await ElMessageBox.alert(data.issues.slice(0, 100).join("\n"), "导入提示", { confirmButtonText: "我已知晓" }); importDialog.value = false; importFile.value = undefined; uploadRef.value?.clearFiles(); await loadStudents(); await loadFinal(); }
async function generateFinal() { if (!clazzId.value) return; await generateQualityFinal(clazzId.value); ElMessage.success("最终评定已重新计算"); await loadFinal(); finalDialog.value = true; }
async function toggleFinalLock() { if (!clazzId.value) return; const next = !Boolean(finalState.value.isLocked); await lockQualityFinal(clazzId.value, next); ElMessage.success(next ? "最终评定已锁定" : "最终评定已解锁"); await loadFinal(); }
async function openFinal() { await loadFinal(); finalDialog.value = true; }
async function changeFinalLevel(row: any, level: string) { if (!clazzId.value || finalState.value.isLocked) return; await updateQualityFinalLevel(clazzId.value, row.studentId, row.dimension, level); ElMessage.success("最终等级已调整"); }
function doExport() { if (!clazzId.value) return ElMessage.warning("请先选择班级"); exportQualityWorkbook(clazzId.value).then((response: any) => { const blob = new Blob([response.data], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "初中综合素质评价-班级名单.xlsx"; link.click(); URL.revokeObjectURL(url); }); }
function classLabel(item: any) { return `${item.gradeName ?? ""} ${item.name ?? ""}`.trim(); }
async function changeClass() { await loadStudents(); await loadFinal(); }
onMounted(async () => { const { data } = await getQualityConfig(); config.value = data; resetMatrix(); await loadClasses(); await loadFinal(); });
</script>
<template>
  <div class="app-container quality-page"><el-card shadow="never">
    <template #header><div class="card-header"><span>初中综合素质评价</span><span class="header-tip">按班级名单维护，学号优先匹配学生</span></div></template>
    <el-form inline class="toolbar"><el-form-item label="初中班级"><el-select v-model="clazzId" class="class-select" placeholder="请选择班级" @change="changeClass"><el-option v-for="item in classes" :key="item.id" :label="classLabel(item)" :value="item.id" /></el-select></el-form-item><el-button type="primary" @click="importDialog = true"><i-ep-upload />导入评价名单</el-button><el-button @click="doExport"><i-ep-download />导出名单/评价</el-button><el-button type="warning" plain @click="generateFinal">重新计算最终评定</el-button><el-button plain @click="openFinal">查看最终评定</el-button><span class="toolbar-tip">支持六个学期工作表，空白评价自动按 N/A 导入</span></el-form>
    <el-row :gutter="16"><el-col :span="8"><el-table :data="students" border highlight-current-row height="560" @current-change="selectStudent"><el-table-column type="index" width="52" label="#" /><el-table-column prop="code" label="学号" width="120" /><el-table-column prop="name" label="姓名" /><el-table-column prop="completedSemesters" label="已录学期" width="90" align="center" /><template #empty><el-empty description="该班级暂无学生" /></template></el-table></el-col>
      <el-col :span="16"><el-empty v-if="!selectedStudent" description="请从左侧选择学生" :image-size="100" /><template v-else><div class="student-title"><span>{{ selectedStudent.name }}（{{ selectedStudent.code }}）</span><el-button type="primary" :loading="loading" @click="saveAll">保存全部学期评价</el-button></div><el-table :data="config.semesters.map((s: string) => ({ semester: s }))" border><el-table-column prop="semester" label="学期" width="130"><template #default="scope">{{ scope.row.semester.replace("junior_", "初").replace("_1", "上").replace("_2", "下") }}</template></el-table-column><el-table-column v-for="dimension in config.dimensions" :key="dimension" :label="dimension" min-width="110"><template #default="scope"><el-select v-model="matrix[scope.row.semester][dimension]" size="small"><el-option v-for="level in config.entryLevels" :key="level" :label="level" :value="level" /></el-select></template></el-table-column></el-table><el-descriptions title="五维累计分" :column="5" border class="summary"><el-descriptions-item v-for="dimension in config.dimensions" :key="dimension" :label="dimension">{{ Number(summary.dimensionTotals?.[dimension] ?? 0).toFixed(2) }}</el-descriptions-item></el-descriptions><el-table :data="records" border size="small" class="records"><el-table-column prop="semester" label="学期" /><el-table-column prop="dimension" label="维度" /><el-table-column prop="level" label="等级" /><el-table-column prop="comment" label="备注" /></el-table></template></el-col></el-row>
  </el-card><el-dialog v-model="importDialog" title="导入综合素质评价名单" width="520px"><p class="dialog-tip">请使用六个学期工作表的 Excel。每张表至少包含“学号/考号、姓名”和五个维度列；系统会优先按学号匹配，再按唯一姓名匹配。</p><el-upload ref="uploadRef" drag :auto-upload="false" :limit="1" accept=".xlsx,.xls" :on-change="chooseFile" :on-exceed="(files: any[]) => { uploadRef?.clearFiles(); chooseFile(files[0]); }"><i-ep-upload-filled /><div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div></el-upload><template #footer><el-button @click="importDialog = false">取消</el-button><el-button type="primary" @click="doImport">开始导入</el-button></template></el-dialog><el-dialog v-model="finalDialog" title="最终评定" width="900px"><div class="final-toolbar"><span>状态：<el-tag :type="finalState.isLocked ? 'success' : 'warning'">{{ finalState.isLocked ? '已锁定' : '未锁定' }}</el-tag></span><el-button size="small" @click="toggleFinalLock">{{ finalState.isLocked ? '解锁' : '锁定结果' }}</el-button></div><el-table :data="finalRows" border max-height="520"><el-table-column prop="code" label="学号" width="120" /><el-table-column prop="name" label="姓名" width="100" /><el-table-column prop="dimension" label="维度" width="110" /><el-table-column prop="cumulativeScore" label="累计分" /><el-table-column prop="classRank" label="班级名次" /><el-table-column prop="automaticLevel" label="自动等级" /><el-table-column label="最终等级"><template #default="scope"><el-select v-model="scope.row.finalLevel" size="small" :disabled="Boolean(finalState.isLocked)" @change="changeFinalLevel(scope.row, scope.row.finalLevel)"><el-option label="A" value="A" /><el-option label="B" value="B" /><el-option label="C" value="C" /></el-select></template></el-table-column><el-table-column prop="availableTerms" label="有效学期" /></el-table></el-dialog></div>
</template>
<style scoped>.card-header,.student-title,.final-toolbar{display:flex;align-items:center;justify-content:space-between}.header-tip,.toolbar-tip,.dialog-tip{color:var(--el-text-color-secondary);font-size:13px}.class-select{width:240px}.toolbar{margin-bottom:14px}.student-title{margin-bottom:12px;font-size:16px;font-weight:600}.summary{margin-top:18px}.records{margin-top:18px}.final-toolbar{margin-bottom:12px}</style>
